spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./db/messageDb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: msg
    password:
    driverClassName: org.h2.Driver
  application:
    name: fe-core-challenge
  server:
    port: 8888

